### ISSUE TITLE
[Feature] `testnet2` checklist

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkVM#233]
## 🚀 Feature

`testnet2` todos are as follows:

Core changes:
- [x] #228
    - [x] #241 
    - [x] #251
- [x] #264 
- [x] #271 

Ledger changes:
- [x] #272 
- [ ] #273
- [ ] #280 
- [x] #305 
- [x] #307

Transaction changes:
- [x] #229
    - [x] #258 
- [x] #270 
- [x] #304
- [ ] Add Marlin universal parameters, and update the integration test to reflect it
- [x] Fix the Marlin inputs for constraints (@weikengchen)
- [x] Offline/Online update for signing
- [x] Remove program commitments from final transaction struct
- [ ] Bake in network ID enforcement in inner circuit
- [x] Increase memo size to 64 bytes

Record changes:
- [x] #306
- [x] Increase the payload size to 128 bytes
    - [x] #288 
- [x] Remove serial number nonce randomness
    - [x] #297

**Comment by howardwu** [comment]
#241
