### ISSUE TITLE
[Tracking] Security Updates

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkVM#677]
## 🚀 Feature

This issue will track all of the pending and completed security related PRs.

- [ ] Sparse polynomial sorting - #660
- [ ] Zip safety - #661 
- [x] Coefficient to biginteger out of bounds - #655 
     - https://github.com/AleoHQ/snarkVM/pull/655/files#diff-65c324b0c9a766e87a9021bb7110133f9c423fa069bf34c2ac2fbff03167940fR561-R571
- [ ] Groth16 prover panics when r equals zero - #678

**Comment by raychu86** [comment]
Closed in favor of PR #679
